apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
spec:
  schedule: "01 00 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector: 
            node-role.kubernetes.io/etcd: "true"
          tolerations: 
          - key: node-role.kubernetes.io/controlplane
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          - key: node-role.kubernetes.io/etcd
            operator: "Equal"
            value: "true"
            effect: "NoExecute"
          containers:
          - name: etcdctl
            image: rancher/coreos-etcd:v3.4.3-rancher1
            imagePullPolicy: IfNotPresent
            env: 
            - name: cluster
              value: Dev
            - name: HOSTIP
              valueFrom: 
                fieldRef: 
                   fieldPath: status.hostIP
            volumeMounts: 
              - mountPath: /ssl 
                name: certs
              - mountPath: /bkp
                name: bkp
            command:
            - /bin/sh
            - -c
            - export DATAREF=`date +"%Y-%m-%d"`; etcdctl snapshot save /bkp/ETCD/$cluster/DB/etcd-snapshot-$DATAREF.db --endpoints=https://$$HOSTIP:2379  --cacert=/ssl/kube-ca.pem  --cert=/ssl/kube-node.pem  --key=/ssl/kube-node-key.pem; find /bkp/ETCD/$cluster/DB/* -daystart -mtime +2 -delete
          restartPolicy: OnFailure
          volumes: 
          - name: certs
            hostPath:
              path: /etc/kubernetes/ssl
              type: Directory
          - name: bkp
            persistentVolumeClaim: 
              claimName: backup-nfs-claim
