apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
spec:
  schedule: "* */8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcdctl
            image: rancher/coreos-etcd:v3.4.3-rancher1
            imagePullPolicy: IfNotPresent
            env: 
            - name: HOSTETCD
              value: "10.10.10.35" 
            - name: HOSTIP
              valueFrom: 
                fieldRef: 
                   fieldPath: status.hostIP
            volumeMounts: 
              - mountPath: /ssl 
                name: certs
              - mountPath: /bkp
                name: bkp
            command:
              - /bin/sh
              - -c
              - export DATAREF=`date +"%Y-%m-%d"`; etcdctl snapshot save /bkp/ETCD/DB/etcd-snapshot-$DATAREF.db --endpoints=https://$HOSTETCD:2379  --cacert=/ssl/kube-ca.pem  --cert=/ssl/kube-node.pem  --key=/ssl/kube-node-key.pem; find /bkp/ETCD/DB/* -daystart -mtime +2 -delete
          restartPolicy: OnFailure
          volumes: 
          - name: certs
            hostPath:
              path: /etc/kubernetes/ssl
              type: Directory
          - name: bkp
            persistentVolumeClaim: 
              claimName: backup-nfs-claim

